#!/usr/bin/env node
// prebuild.js - increments build number and writes BuildInfo.ts

const fs = require('fs');
const path = require('path');

const counterFile = path.join(__dirname, '.build-number');
const outFile = path.join(__dirname, 'src', 'BuildInfo.ts');

let buildNumber = 1;
if (fs.existsSync(counterFile)) {
    buildNumber = parseInt(fs.readFileSync(counterFile, 'utf8').trim(), 10) + 1;
}
fs.writeFileSync(counterFile, String(buildNumber));

const now = new Date();
const timestamp = now.toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

fs.writeFileSync(outFile, `// Auto-generated by prebuild.js — do not edit
export const BUILD_NUMBER = ${buildNumber};
export const BUILD_DATE = '${timestamp}';
`);

console.log(`Build #${buildNumber} — ${timestamp}`);
